# mapping of services to controller classes
services:
    bbdkp.bbguild.controller:
        class: bbdkp\bbguild\controller\view_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '%core.php_ext%'
    bbdkp.bbguild.admin.controller:
        class: bbdkp\bbguild\controller\admin_controller
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@pagination'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.php_ext%'
    bbdkp.bbguild.listener:
        class: bbdkp\bbguild\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
        tags:
            - { name: event.listener }
